# Generated by Django 4.2.13 on 2024-06-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=12)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cad', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
